sudo: false
dist: trusty

language: python

services: 
  docker

python:
 - "3.5"

before_install:
  - pip install --upgrade pip 

install:
  - pip install autopep8
  - pip install coverage
  - pip install numpy
  - pip install pylint

before_script:
  - uname -a
  - printenv | sort
  - make versions

script:
  - docker-compose up -d
  - docker exec -it startupfairy bash
  - make test

notifications:
  email: false
